services:
  web:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080